ALTER TABLE tOption ADD COLUMN cContext VARCHAR(20) DEFAULT '' AFTER cLabel;
UPDATE tOption SET cContext='DALEA_CONTEXT';
UPDATE tOption SET cContext=NULL WHERE cUrl IS NULL;

UPDATE tOption SET cContext='TIMECTRL_CONTEXT' WHERE cKey = 'TURN';
UPDATE tOption SET cContext='TIMECTRL_CONTEXT' WHERE cKey = 'FISCAL_DATE';
UPDATE tOption SET cContext='TIMECTRL_CONTEXT' WHERE cKey = 'MACHINE';
UPDATE tOption SET cContext='TIMECTRL_CONTEXT' WHERE cKey = 'LICENSE_CAUSE';
UPDATE tOption SET cContext='TIMECTRL_CONTEXT' WHERE cKey = 'SUMMARY';
UPDATE tOption SET cContext='TIMECTRL_CONTEXT' WHERE cKey = 'REP_ASIST';
UPDATE tOption SET cContext='TIMECTRL_CONTEXT' WHERE cKey = 'REP_WEEKLY';
UPDATE tOption SET cContext='TIMECTRL_CONTEXT' WHERE cKey = 'REP_PLAIN';
UPDATE tOption SET cContext='TIMECTRL_CONTEXT' WHERE cKey = 'REP_LATE';
UPDATE tOption SET cContext='TIMECTRL_CONTEXT' WHERE cKey = 'REP_ABSENCE';
UPDATE tOption SET cContext='TIMECTRL_CONTEXT' WHERE cKey = 'REP_CFG_OUT_TYPE';
UPDATE tOption SET cContext='TIMECTRL_CONTEXT' WHERE cKey = 'REP_LIST';
UPDATE tOption SET cContext='TIMECTRL_CONTEXT' WHERE cKey = 'EXECUTE_REPORT';
UPDATE tOption SET cContext='TIMECTRL_CONTEXT' WHERE cKey = 'GROUP_MGR';
UPDATE tOption SET cContext='TIMECTRL_CONTEXT' WHERE cKey = 'EMPLOYEE_DATA';
UPDATE tOption SET cContext='TIMECTRL_CONTEXT' WHERE cKey = 'EMPLOYEE_LICENSE';
UPDATE tOption SET cContext='TIMECTRL_CONTEXT' WHERE cKey = 'EMPLOYEE_TURN';
UPDATE tOption SET cContext='TIMECTRL_CONTEXT' WHERE cKey = 'EMPLOYEE_MARK';
UPDATE tOption SET cContext='TIMECTRL_CONTEXT' WHERE cKey = 'EMPLOYEE_DETACHED';

#UPDATE tOption SET cContext='DALEA_CONTEXT' WHERE cKey = 'EMPLOYEE_DATA';
#ALTER TABLE tEmployee CHANGE COLUMN cRut cRut VARCHAR(11) UNIQUE;

UPDATE tVersion SET cVersion='1.2.26', cUpdated=NOW() WHERE cKey = 'DBT';
