ALTER TABLE tTurnDay 
ADD COLUMN cEdgePrevIn INTEGER NOT NULL DEFAULT '0' AFTER cBusinessDay,
ADD COLUMN cEdgePostIn INTEGER NOT NULL DEFAULT '0' AFTER cStartTime;

ALTER TABLE tTurnDay 
ADD COLUMN cEdgePrevOut INTEGER NOT NULL DEFAULT '0' AFTER cEdgePostIn,
ADD COLUMN cEdgePostOut INTEGER NOT NULL DEFAULT '0' AFTER cEndTime;
